using Qalam.Common.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Qalam.MYSQL.Entities
{
    public class Exam
    {
        public Exam()
        {
            Questions = new HashSet<ExamQuestion>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int TimeInMinutes { get; set; }
        public EStartTime? StartTime { get; set; }

        [ForeignKey("Video")]
        public int? VideoId { get; set; }  // null if it generated by system
        public virtual LiveStream Video { get; set; }

        [Required]
        [ForeignKey("Course")]
        public int CourseId { get; set; }
        public virtual Course Course { get; set; }

        [ForeignKey("Setter")]
        public int? SetterId { get; set; }  // null if it generated by system
        public virtual Teacher Setter { get; set; }

        public virtual ICollection<ExamQuestion> Questions { get; set; }
        public virtual ICollection<StudentExam> Students { get; set; }
    }
}
