using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Qalam.MYSQL.Entities
{
    public class Notification
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }
        [Required]
        public DateTime ReleaseDate { get; set; }
        public bool IsRead { get; set; }
        public DateTime? ReadTime { get; set; }
        public string Url { get; set; }
        [Required]
        public string Message { get; set; }

        [ForeignKey("Receiver")]
        public int ReceiverId { get; set; }
        public virtual User Receiver { get; set; }

        [ForeignKey("Sender")]
        public int? SenderId { get; set; }  // null if it generated by system
        public virtual User Sender { get; set; }
    }
}
